"""Generate the reverse-direction UTM route map from route_map.csv.

params.yaml picks the direction of travel from the sign of the easting change,
so it needs the route in both directions. artifacts/route already ships
route_map.csv (UTM 37N, easting decreasing) and the judge-frame pair
route_map_fwd/rev.csv, but the judge-frame pair is in the organiser's local
metric frame and the UTM pair was never produced.

This writes route_map_rev_utm.csv: route_map.csv with the point order reversed
and the arc length recomputed from the start of the reversed polyline, which is
what PathMap::finalise() does anyway. Keeping the map in UTM means the published
origin subtraction is exact instead of relying on a fitted constant.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

R = Path(r"D:\hactaton\backup-odometry\artifacts\route")
SRC = R / "route_map.csv"
DST = R / "route_map_rev_utm.csv"


def main() -> None:
    rows: list[list[float]] = []
    header: list[str] = []
    for line in SRC.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s:
            continue
        if s.startswith("#"):
            header.append(s)
            continue
        rows.append([float(x) for x in s.split(",")])

    a = np.asarray(rows, dtype=float)
    print(f"source      {SRC.name}: {a.shape[0]} points, columns {a.shape[1]}")
    print(f"  x {a[0,0]:.1f} -> {a[-1,0]:.1f}  (easting {'decreasing' if a[-1,0] < a[0,0] else 'increasing'})")

    b = a[::-1].copy()

    # Recompute arc length along the reversed order. PathMap::finalise() does the
    # same, but the column is written so the file is self-describing.
    seg = np.hypot(np.diff(b[:, 0]), np.diff(b[:, 1]))
    s = np.concatenate([[0.0], np.cumsum(seg)])
    b[:, 3] = s

    print(f"reversed    x {b[0,0]:.1f} -> {b[-1,0]:.1f}  (easting "
          f"{'decreasing' if b[-1,0] < b[0,0] else 'increasing'})")
    print(f"  length {s[-1]:.1f} m, step {seg.min():.3f}..{seg.max():.3f} m")

    # Round-trip check: reversing twice must give the original geometry back.
    seg_rt = np.hypot(np.diff(b[::-1, 0]), np.diff(b[::-1, 1]))
    print(f"  round-trip length {seg_rt.sum():.1f} m, max |ds| difference "
          f"{np.abs(seg_rt - seg).max():.6f} m")

    out = list(header)
    out.append("# Reverse direction, same frame as the source. Generated by "
               "tools/build_reverse_map.py; PathMap::finalise() recomputes s, "
               "heading, grade and curvature from the geometry.")
    for row in b:
        out.append(",".join(f"{v:.3f}" if i == 2 else f"{v:.3f}" for i, v in enumerate(row)))
    DST.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote       {DST}  ({DST.stat().st_size} bytes, {b.shape[0]} points)")


if __name__ == "__main__":
    main()
